repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        description: The uncompromising Python code formatter

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: isort is a Python utility to sort imports alphabetically and separate into sections and by type.

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        description: A formatter for finding and removing unused import statements.
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Ensure that code don't have trailing whitespace
      - id: check-ast
        name: Check python abstract syntax trees
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-json
        name: Check JSON files format
      - id: check-merge-conflict
        description: Check for merge conflicts in code
      - id: end-of-file-fixer
        description: Files should end with empty line
        exclude: ".json"
      - id: check-yaml
        description: checks yaml files for parseable syntax
      - id: debug-statements
        description: checks for debugger imports and py37+ `breakpoint()` calls in python source.

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        description: flake8 is a command-line utility for enforcing style consistency across Python projects.
        additional_dependencies:
          - flake8-print
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        description: Automatically run terraform fmt on all Terraform code (*.tf files).
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
